#index:
#    path: /
#    controller: App\Controller\DefaultController::index
currency_list:
    path:       /
    controller: App\Controller\CurrencyController::latest
    methods:    GET
currency_item:
    path:       /{name}
    controller: App\Controller\CurrencyController::item
    methods:    GET

api_currency_by_name:
    path:       /api/currency/{name}
    controller: App\Controller\ApiDataController::getByName
    methods:    GET